#!/usr/bin/env bash
# -*- mode: sh; coding: utf-8 -*-
ME="${0##*/}"
##############################################################################
# This program is free software; you can redistribute it and/or modify it    #
# under the terms of the GNU General Public License as published by the Free #
# Software Foundation; either version 3 of the License, or (at your option)  #
# any later version.                                                         #
#                                                                            #
# This program is distributed in the hope that it will be useful, but with-  #
# out any warranty; without even the implied warranty of merchantability or  #
# fitness for a particular purpose.  See the GNU General Public License for  #
# more details.  <http://gplv3.fsf.org/>                                     #
##############################################################################

MY_APPNAME='kbmsgr-post'
MY_AUTHOR='Klaus Alexander Seistrup <klaus@seistrup.dk>'
MY_REVISION='2016-08-26'
MY_VERSION="0.0.1 (${MY_REVISION})"
MY_COPYRIGHT="\
kbmsgr-post/${MY_VERSION}
Copyright © 2016 ${MY_AUTHOR}

This is free software; see the source for copying conditions.  There is no
warranty; not even for merchantability or fitness for a particular purpose.\
"
MY_HELP="
usage: ${ME} [OPTIONS] <MYFILE> <TEXT>

positional arguments:
  MYFILE            full path of my messages file
  TEXT              my message line

options:
  -h, --help        display this help and exit
  -v, --version     output version information and exit
  -c, --copyright   show copying policy and exit
"

die () {
  [[ -n "${1}" ]] && {
    echo "${ME}:" "${@}" >&2
    exit 1
  }
  exit 0
}

my_help () {
  echo "${MY_HELP}"
}

my_version () {
  echo "${MY_APPNAME}/${MY_VERSION}"
}

my_copyright () {
  echo "${MY_COPYRIGHT}"
}

append_line () {
  local myfile="${1}"
  local mytext="${2}"
  local mytemp="/dev/shm/kbmsgr-${myfile##*/}"
  local mylock="${mytemp}..LCK"
  local mymask
  local utcnow

  utcnow=$(date --utc '+%Y-%m-%dT%H:%M:%SZ')
  mymask=$(umask)

  umask 0027

  lockfile "${mylock}" || {
    die "cannot obtain lock: ${mylock}"
  }

  cat "${myfile}" > "${mytemp}" || {
    rm -f "${mylock}"
    die "cannot create temporary file: ${mytemp}"
  }

  printf '%s\t%s\n' "${utcnow}" "${mytext}" >> "${mytemp}" || {
    rm -f "${mylock}"
    die "cannot append message to temporary file: ${mytemp}"
  }

  mv "${mytemp}" "${myfile}" || {
    rm -f "${mylock}"
    die "cannot update file: ${myfile}"
  }

  rm -f "${mylock}"
  umask "${mymask}"
}

main () {
  local myfile="${1}"
  local mytext=''

  shift
  mytext="${*}"

  case "${1}" in
    -h | --help )
      my_help
      die
    ;;
    -v | --version )
      my_version
      die
    ;;
    -c | --copyright )
      my_copyright
      die
    ;;
    -* )
      die "unrecognized option ‘${1}’"
    ;;
  esac

  [[ -z "${myfile}" ]] && die "missing positional argument: MYFILE"
  [[ -z "${mytext}" ]] && die # exit silently

  append_line "${myfile}" "${mytext}"
  exit 0
}

main "${@}"

:
# eof
