#!/usr/bin/env bash
# -*- mode: sh; coding: utf-8 -*-
ME="${0##*/}"
MY_PROMPT='>>> '
##############################################################################
# This program is free software; you can redistribute it and/or modify it    #
# under the terms of the GNU General Public License as published by the Free #
# Software Foundation; either version 3 of the License, or (at your option)  #
# any later version.                                                         #
#                                                                            #
# This program is distributed in the hope that it will be useful, but with-  #
# out any warranty; without even the implied warranty of merchantability or  #
# fitness for a particular purpose.  See the GNU General Public License for  #
# more details.  <http://gplv3.fsf.org/>                                     #
##############################################################################

MY_APPNAME='kbmsgr-prompt'
MY_AUTHOR='Klaus Alexander Seistrup <klaus@seistrup.dk>'
MY_REVISION='2016-08-26'
MY_VERSION="0.1.0 (${MY_REVISION})"
MY_COPYRIGHT="\
kbmsgr-prompt/${MY_VERSION}
Copyright © 2016 ${MY_AUTHOR}

This is free software; see the source for copying conditions.  There is no
warranty; not even for merchantability or fitness for a particular purpose.\
"
MY_HELP="\
usage: ${ME} [OPTIONS] <MYFILE>

positional argument:
  MYFILE            full path of my messages file

options:
  -h, --help        display this help and exit
  -v, --version     output version information and exit
  -c, --copyright   show copying policy and exit\
"

die () {
  rc=0
  [[ -n "${1}" ]] && {
    echo "${ME}:" "${@}" >&2
    rc=1
  }
  exit "${rc}"
}

kill_tmux () {
  # Kill entire session if it exists
  tmux ls | grep -q '^kbmsgr:' && {
    tmux kill-session -t 'kbmsgr' || :
  }
}

my_help () {
  echo "${MY_HELP}"
}

my_version () {
  echo "${MY_APPNAME}/${MY_VERSION}"
}

my_copyright () {
  echo "${MY_COPYRIGHT}"
}

my_post () {
  local myfile="${1}"
  local message
  local cr

  cr=$(printf '\r')

  read -r -e -p "${cr}${MY_PROMPT}" -i "${message}" message

  [[ -n "${message}" ]] && {
    [[ "${message}" == "." ]] && die
    kbmsgr-post "${myfile}" "${message}" && {
      printf '\x1b[2m%s\x1b[0m' "${message}"
    }
  }
}

main () {
  local myfile="${1}"

  case "${1}" in
    -h | --help )
      my_help
      die
    ;;
    -v | --version )
      my_version
      die
    ;;
    -c | --copyright )
      my_copyright
      die
    ;;
    -* )
      die "unrecognized option ‘${1}’"
    ;;
  esac

  [[ -z "${myfile}" ]] && die "missing positional argument: MYFILE"

  clear
  echo "Press ^C to exit when you're all done"

  while :
  do
    my_post "${myfile}"
  done
}

trap 'kill_tmux' EXIT SIGQUIT SIGTERM
main "${@}"
die

# eof
