#!/usr/bin/env bash
# -*- mode: sh; coding: utf-8 -*-
ME="${0##*/}"
MYPATH="${0}"
##############################################################################
# This program is free software; you can redistribute it and/or modify it    #
# under the terms of the GNU General Public License as published by the Free #
# Software Foundation; either version 3 of the License, or (at your option)  #
# any later version.                                                         #
#                                                                            #
# This program is distributed in the hope that it will be useful, but with-  #
# out any warranty; without even the implied warranty of merchantability or  #
# fitness for a particular purpose.  See the GNU General Public License for  #
# more details.  <http://gplv3.fsf.org/>                                     #
##############################################################################

MY_APPNAME='kbmsgr'
MY_AUTHOR='Klaus Alexander Seistrup <klaus@seistrup.dk>'
MY_REVISION='2016-08-20'
MY_VERSION="0.0.1 (${MY_REVISION})"
MY_COPYRIGHT="\
kbmsgr/${MY_VERSION}
Copyright © 2016 Klaus Alexander Seistrup <klaus@seistrup.dk>

This is free software; see the source for copying conditions.  There is no
warranty; not even for merchantability or fitness for a particular purpose.\
"
MY_HELP="\
usage: ${ME} [OPTIONS] <SELF> <OTHER>

positional arguments:
  SELF              your keybase username
  OTHER             recipient's keybase username

options:
  -h, --help        display this help and exit
  -v, --version     output version information and exit
  -c, --copyright   show copying policy and exit\
"

die () {
  [[ -n "${1}" ]] && {
    echo "${ME}:" "${@}" >&2
    exit 1
  }
  exit 0
}

my_help () {
  echo "${MY_HELP}"
}

my_version () {
  echo "${MY_APPNAME}/${MY_VERSION}"
}

my_copyright () {
  echo "${MY_COPYRIGHT}"
}

main () {
  local tui="${MYPATH}-tui"
  local self="${1}"
  local other="${2}"
  local kbroot='/keybase/private'
  local msgdir

  case "${1}" in
    -h | --help )
      my_help
      die
    ;;
    -v | --version )
      my_version
      die
    ;;
    -c | --copyright )
      my_copyright
      die
    ;;
    -* )
      die "unrecognized option ‘${1}’"
    ;;
  esac

  [[ -z "${other}" ]] && die 'missing positional argument: OTHER'
  [[ -z "${self}" ]] && die 'missing positional argument: SELF'

  if [[ -d "${kbroot}/${other},${self}/." ]]; then
    msgdir="${kbroot}/${other},${self}/messages"
  else
    msgdir="${kbroot}/${self},${other}/messages"
  fi

  [[ -d "${msgdir}" ]] || {
    mkdir -p "${msgdir}" \
    || die "cannot create directory ‘${msgdir}’"
    touch "${msgdir}/${self}.txt" \
    || die "cannot create file ‘${msgdir}/${self}.txt’"
    touch "${msgdir}/${other}.txt" \
    || die "cannot create file ‘${msgdir}/${other}.txt’"
  }

  [[ -x "${tui}" ]] && {
    exec "${tui}" "${self}" "${other}" "${msgdir}"
  }
  die "cannot find ${tui}"
}

main "${@}"

:
# eof
